services:
  memlord:
    image: ghcr.io/myrikld/memlord:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/onnx:/app/src/memlord/onnx
    env_file:
      - .env
#    environment:
#      - REEMBED=1
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memlord
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "memlord", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
