"""empty message

Revision ID: 84634a3eaf8d
Revises: f8c1fc9be252
Create Date: 2026-06-09 13:01:08.861465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84634a3eaf8d'
down_revision: Union[str, Sequence[str], None] = 'f8c1fc9be252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_email_tokens_user_id_users'), 'email_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_memories_created_by_users'), 'memories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_memories_created_by_users'), 'memories', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_oauth_clients_user_id_users'), 'oauth_clients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_oauth_clients_user_id_users'), 'oauth_clients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_workspace_invites_used_by_users'), 'workspace_invites', type_='foreignkey')
    op.drop_constraint(op.f('fk_workspace_invites_created_by_users'), 'workspace_invites', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspace_invites_created_by_users'), 'workspace_invites', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_workspace_invites_used_by_users'), 'workspace_invites', 'users', ['used_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_workspaces_created_by_users'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspaces_created_by_users'), 'workspaces', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workspaces_created_by_users'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspaces_created_by_users'), 'workspaces', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_workspace_invites_used_by_users'), 'workspace_invites', type_='foreignkey')
    op.drop_constraint(op.f('fk_workspace_invites_created_by_users'), 'workspace_invites', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspace_invites_created_by_users'), 'workspace_invites', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('fk_workspace_invites_used_by_users'), 'workspace_invites', 'users', ['used_by'], ['id'])
    op.drop_constraint(op.f('fk_oauth_clients_user_id_users'), 'oauth_clients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_oauth_clients_user_id_users'), 'oauth_clients', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_memories_created_by_users'), 'memories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_memories_created_by_users'), 'memories', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('fk_email_tokens_user_id_users'), 'email_tokens', type_='foreignkey')
    # ### end Alembic commands ###
